# SITE CONFIGURATION
baseurl: ""
url: "https://ai-dgist.github.io"

# THEME-SPECIFIC CONFIGURATION
title: 협동과정 인공지능 전공                                   # site's title
description: "디지스트 AI 대학원"      # used by search engines
avatar: assets/img/dgist-97-30.svg                         # Empty for no avatar in navbar
color_theme: auto

# Header and footer text
header_text: DGIST AI Graduate School
header_feature_image: assets/img/header/svisual01.jpeg
header_feature_image_responsive: true
footer_text: 42988 대구광역시 달성군 현풍읍 테크노중앙대로 333 <br> COPYRIGHT 2022 DGIST. ALL RIGHTS RESERVED.

# Blog
excerpt: true                                           # Or "truncate" (first 250 characters), "false" to disable
post_navigation: true
color_image: /assets/img/lineart.png                    # A bit transparent for color posts.

# Features
# More in the _data folder for share buttons, author and language
# For layout customization, go to the "_sass > base" folder, and check "_variables.scss"
katex: true                                             # Enable if using math markup
mermaid: true                                           # Enable mermaid-js for sequence and diagrams
google_analytics:                                       # Tracking ID, e.g. "UA-000000-01"
cookie_consent: false                                   # To respect the usage of cookies
color_theme: auto                                       # auto, dark or light

# Comments
comments:
  disqus_shortname:                                     # Your discus shortname for comments
  cusdis_app_id:                                        # Your cusdis data-app-id
  utterances:                                           # Enable by filling below information. For more info, go to https://utteranc.es
    repo:                                               # your public comments repository (e.g. owner/repo)
    issue-term:                                         # Issue term (e.g. "comment" consider issues with this word in the title as comments)

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# PORTFOLIO
collections:
  portfolio:
    output: true
    permalink: /:collection/:name

# BUILD SETTINGS
sass:
  style: compressed
plugins: [jekyll-paginate, jekyll-seo-tag, jekyll-feed]
exclude: [".jekyll-cache", ".jekyll-metadata", ".idea", "vendor/*", "assets/node_modules/*"]

# theme: type-on-strap                                  # if using the theme as a jekyll theme gem
remote_theme: sylhare/Type-on-Strap                     # If using as a remote_theme in github
